Store/StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServicesManager _manager;
        private readonly Cart _cart;

        public OrderController(IServicesManager manager, Cart cart)
        {
            _manager = manager;
            _cart = cart;
        }

        
        [Authorize]
        public ViewResult Checkout() => 
        View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty");
            }
            if(ModelState.IsValid){
                order.Lines=_cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete",new {OrderId=order.OrderId});
            }
            else{
                return View();
            }
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServicesManager _manager;

        public Cart Cart { get; set; } // Sepetteki bilgileri getirmek için IoC kaydı gerçekleştirilecek.
        public CartModel(IServicesManager manager, Cart cartService)
        {
            _manager = manager;
            Cart=cartService;
        }


        /* 
         Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();//Eğer cart varsa üzerine yazacak yoksa yeni bir nesne üretecek.

         bu şekilde her mettota cart kontrolünü ortadan kaldırmak için cartSession adında bir implementsion ile bunu kontrol edebiliyoruz. kolay bir şekilde.
         */


        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();//Eğer cart varsa üzerine yazacak yoksa yeni bir nesne üretecek.
        }
        public IActionResult OnPost(int productId, string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(productId, false);
            if (product is not null)
            {
                //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                Cart.AddItem(product, 1);
               // HttpContext.Session.SetJson<Cart>("cart", Cart);
            }
            return RedirectToPage(new {returnUrl=returnUrl});
        }
        public IActionResult OnPostRemove(int id, string returnUrl)
        {
          //  Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductId.Equals(id)).Product);
          //  HttpContext.Session.SetJson<Cart>("cart",Cart);
            return Page();
        }
    }
}

Store/StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages{
    public class DemoModel:PageModel{
        public String? FullName => HttpContext?.Session?.GetString("name")?? "Please to be Login" ;
        
        
        public void Onget(){

        }
        public void OnPost([FromForm]string name){
            HttpContext.Session.SetString("name",name);
        }
        public void Close(){
            HttpContext.Session.Remove("name");
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml
@page "/Cart"
@model CartModel


<div
    class="container bg-gradient bg-dark mb-2 my-2"
>
    

<div
    class="table-responsive-md mx-5 my-5"
>
<div class="text-center">
    <h3 class="d-inline-block bg-warning fw-bold rounded-circle border border-dark p-2">CART</h3>
</div>
    <table>
        <thead class="table-info fs-4 text-center">
            <tr class="text-center">
                <th>Product </th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody class="text-center fw-bold">
            @foreach(var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>()){
                <tr>

                <td>@line.Product.ProductName 
                    <img height="100" width="75" src="@line.Product.ImageUrl" alt="@line.Product.ImageUrl"/>
                    </td>
                <td>@line.Quantity</td>
                <td>@line.Product.Price.ToString("c")</td>
                <td>@((line.Product.Price*line.Quantity).ToString("c2"))</td>
                <td>

                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="id" value="@line.Product.ProductId"/>
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl"/>
                        <button type="submit" class="btn btn-outline-danger fw-bold text-secondary">
                           <i class="text-danger fa fa-trash px-1"></i> Delete
                        </button>
                    </form>




                    @* <div class="btn-group gap-2 rounded">
                        <button class="btn btn-outline-success" type="button">
                            View
                        </button>
                        <button class="btn btn-outline-danger rounded" type="button">
                            Delete
                        </button>
                    </div> *@
                </td>
                </tr>
            }
           
          
        </tbody>
        <tfoot class="text-right">
            <td colspan="3" class="text-right fw-bold text-dark bg-light">
                 <div class="d-inline-block border border-3 border-danger rounded p-1 bg-light">
Total :            </div>
            </td>
            <td class="bg-light">
            </td>
            <td colspan="" class="text-right text-dark fw-bold bg-light">
            <div class="d-inline-block border border-3 border-danger rounded p-1 bg-light">
                @Model.Cart?.ComputeTotalValue().ToString("c2")
            </div>
            </td>
        </tfoot>
    </table>
    <div class="text-center">

    <div class="btn-group my-2">
        <a class="btn btn-outline-primary mx-auto text-center" href="@Model?.ReturnUrl">Continue Shopping</a>
        <a class="btn btn-outline-primary mx-auto mx-2 text-center" asp-action="Checkout" asp-controller="Order">Checkout</a>
    </div>
    </div>
</div>
</div>

Store/StoreApp/Pages/Complete.cshtml
@page

<div class="text-center">
    <h6 class="display-6">Thanks</h6>
    <p>Thanks for placing order #@OrderId</p>
    <p>We'll ship your goods as soon as possiple.</p>
    <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">Return To Store</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public String? OrderId { get; set; }
}

Store/StoreApp/Pages/Contact.cshtml
@page "/getintouch"
<div class="text-center mx-auto">

<h2 class="">
    Contact
</h2>
</div>

Store/StoreApp/Pages/Demo.cshtml
@page
@model StoreApp.Pages.DemoModel
@{

}

<div class="text-center w-75 bg-gradient bg-secondary mx-auto">
    <h3 class="text-warning">You are welcome <span class="fw-bolder text-light">
    @Model?.FullName
    </span>
    çıkış ikonu
@while(@Model?.FullName is not null){
    <div role="button" class="d-inline-block text-danger border border-3 border-dark m-2"><i class="fa fa-door-open"></i> Quit</div>
}
    </h3>
    <p>
        @* @HttpContext.Session.GetString("name"); *@
    </p>
@while(@Model?.FullName==""){

    <i class="fa fa-user-circle fa-3x text-dark my-2" aria-hidden="true"></i>
<form method="post" asp-page="/demo">
    <div class="form-group w-50 mx-auto">
        <i class="fa fa-user-secret" aria-hidden="true"></i>
        <input type="text" name="name" placeholder="Name" size="30"/>
    </div>
    <div class="form-group my-2 w-50 mx-auto">

        <i class="fa fa-key" aria-hidden="true"></i>
        <input class="mb-4" type="password" name="password" size="30" placeholder="Password"/>
    </div>
        <button class="btn btn-outline-light">Login</button>
  
</form>
}
</div>